spring:
  redis:
    host: redis
    port: 6379
openweather:
  host: http://api.openweathermap.org
  applicationId: 8bda43274992b81b2e3bd399316b74dd
spotify:
  host: https://accounts.spotify.com
  apiHost: https://api.spotify.com
  clientId: 810d7196f9dd4b19b7dcf3c07d3dbc84
  clientSecret: bb683aaf8f234e2a9774e9b60bf2b6fa

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 2
logging:
  level:
    com.ifood.client.SpotifyClient: DEBUG

