openweather.host : api.openweathermap.org
openweather.applicationId : 8bda43274992b81b2e3bd399316b74dd
spotify.host: https://accounts.spotify.com
spotify.apiHost: https://api.spotify.com
spotify.clientId: 810d7196f9dd4b19b7dcf3c07d3dbc84
spotify.clientSecret: bb683aaf8f234e2a9774e9b60bf2b6fa